-- EOS persistence schema draft (v1)
-- Purpose:
--   First persistence schema slice for the real EOS shift-session endpoint.
--
-- Status:
--   Draft only. This file is intentionally limited to `eos_shift_session`
--   because `POST /api/eos/shift-sessions` is the first persistence endpoint.
--   Accounting-period and report tables are deferred to a later schema step.
--
-- Notes:
--   - PostgreSQL target.
--   - UUID values are expected to be generated by the application layer.
--   - Location-based ownership/concurrency is the primary control model.
--   - Manager takeover / abandonment fields are included now so the first
--     endpoint has the persistence columns it needs for the documented
--     conflict and ownership contract.

BEGIN;

CREATE TABLE IF NOT EXISTS eos_shift_session (
  id UUID PRIMARY KEY,
  location_code TEXT NOT NULL,
  department_code TEXT NOT NULL,
  clinic_code TEXT NOT NULL,
  shift_date DATE NOT NULL,
  shift_start_time TIME NOT NULL,
  opening_cash NUMERIC(12,2) NOT NULL,
  opening_cash_matches BOOLEAN NOT NULL,
  previous_cashbox_end NUMERIC(12,2) NULL,
  corrected_opening_cash NUMERIC(12,2) NULL,
  status TEXT NOT NULL DEFAULT 'open',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by TEXT NOT NULL,
  current_owner TEXT NOT NULL,
  taken_over_from_user TEXT NULL,
  taken_over_at TIMESTAMPTZ NULL,
  takeover_reason TEXT NULL,
  closed_at TIMESTAMPTZ NULL,
  closed_by TEXT NULL,
  abandoned_at TIMESTAMPTZ NULL,
  abandoned_by TEXT NULL,
  abandon_reason TEXT NULL,
  supersedes_shift_session_id UUID NULL REFERENCES eos_shift_session(id) ON DELETE SET NULL,
  superseded_by_shift_session_id UUID NULL REFERENCES eos_shift_session(id) ON DELETE SET NULL,

  CONSTRAINT eos_shift_session_opening_cash_nonnegative_chk
    CHECK (opening_cash >= 0),

  CONSTRAINT eos_shift_session_previous_cashbox_end_nonnegative_chk
    CHECK (
      previous_cashbox_end IS NULL
      OR previous_cashbox_end >= 0
    ),

  CONSTRAINT eos_shift_session_corrected_opening_cash_nonnegative_chk
    CHECK (
      corrected_opening_cash IS NULL
      OR corrected_opening_cash >= 0
    ),

  CONSTRAINT eos_shift_session_corrected_opening_cash_required_chk
    CHECK (
      opening_cash_matches = TRUE
      OR corrected_opening_cash IS NOT NULL
    ),

  CONSTRAINT eos_shift_session_status_chk
    CHECK (
      status IN (
        'open',
        'report_in_progress',
        'submitted',
        'locked',
        'abandoned',
        'superseded'
      )
    )
);

CREATE INDEX IF NOT EXISTS ix_eos_shift_session_location_code
  ON eos_shift_session (location_code);

CREATE INDEX IF NOT EXISTS ix_eos_shift_session_shift_date
  ON eos_shift_session (shift_date);

CREATE INDEX IF NOT EXISTS ix_eos_shift_session_status
  ON eos_shift_session (status);

CREATE INDEX IF NOT EXISTS ix_eos_shift_session_current_owner
  ON eos_shift_session (current_owner);

-- Notes:
--   - Exact "one active shift per location_code" enforcement is still better
--     handled with a partial unique index or trigger once the active-status
--     set is locked in production.
--   - A composite duplicate-protection index on
--     (clinic_code, shift_date, shift_start_time) can be added later if the
--     API-level duplicate check should also be enforced at DB level.
--   - Accounting period, report header, report row, summary, and audit tables
--     are intentionally deferred from this first-endpoint draft.
--   - Supersede linkage columns are included so manager-only unresolved-shift
--     actions can link the old shift to the new shift.

COMMIT;
