-- Seed leave_policies for GEN department for 2025
INSERT INTO leave_policies (year, dept_id, leave_type_id, entitlement_hours, carry_forward_percent, effective_from, created_at)
VALUES
  (2025,
    (SELECT dept_id FROM departments WHERE abbreviation = 'GEN'),
    (SELECT id FROM leave_types WHERE code = 'annual_vacation'),
    224, 50, '2025-01-01', now()),
  (2025,
    (SELECT dept_id FROM departments WHERE abbreviation = 'GEN'),
    (SELECT id FROM leave_types WHERE code = 'urgent_family'),
    32, 0, '2025-04-04', now()),
  (2025,
    (SELECT dept_id FROM departments WHERE abbreviation = 'GEN'),
    (SELECT id FROM leave_types WHERE code = 'sick_leave'),
    80, 0, '2025-01-01', now()),
  (2025,
    (SELECT dept_id FROM departments WHERE abbreviation = 'GEN'),
    (SELECT id FROM leave_types WHERE code = 'maternity_leave'),
    0, 0, '2025-01-01', now()),
  (2025,
    (SELECT dept_id FROM departments WHERE abbreviation = 'GEN'),
    (SELECT id FROM leave_types WHERE code = 'paternity_leave'),
    80, 0, '2025-01-01', now()),
  (2025,
    (SELECT dept_id FROM departments WHERE abbreviation = 'GEN'),
    (SELECT id FROM leave_types WHERE code = 'marriage_leave'),
    16, 0, '2025-01-01', now()),
  (2025,
    (SELECT dept_id FROM departments WHERE abbreviation = 'GEN'),
    (SELECT id FROM leave_types WHERE code = 'bereavement_leave'),
    8, 0, '2025-01-01', now()),
  (2025,
    (SELECT dept_id FROM departments WHERE abbreviation = 'GEN'),
    (SELECT id FROM leave_types WHERE code = 'parental_leave'),
    0, 0, '2025-01-01', now()),
  (2025,
    (SELECT dept_id FROM departments WHERE abbreviation = 'GEN'),
    (SELECT id FROM leave_types WHERE code = 'ivf_leave'),
    100, 0, '2025-01-01', now())
ON CONFLICT (year, dept_id, leave_type_id) DO NOTHING;
